{"uuid": "be751976-3767-41b5-a396-dba56dc098d0", "children": ["317ea4a1-57cf-4ecb-bee8-adcec369edbb"], "befores": [{"name": "web_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=112.0.5615.50)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00EDDCE3+50899]\n\t(No symbol) [0x00E6E111]\n\t(No symbol) [0x00D75588]\n\t(No symbol) [0x00D5D333]\n\t(No symbol) [0x00DBF4DB]\n\t(No symbol) [0x00DCDB33]\n\t(No symbol) [0x00DBB6F6]\n\t(No symbol) [0x00D97708]\n\t(No symbol) [0x00D9886D]\n\tGetHandleVerifier [0x01143EAE+2566302]\n\tGetHandleVerifier [0x011792B1+2784417]\n\tGetHandleVerifier [0x0117327C+2759788]\n\tGetHandleVerifier [0x00F75740+672048]\n\t(No symbol) [0x00E78872]\n\t(No symbol) [0x00E741C8]\n\t(No symbol) [0x00E742AB]\n\t(No symbol) [0x00E671B7]\n\tBaseThreadInitThunk [0x76207D69+25]\n\tRtlInitializeExceptionChain [0x77A7B74B+107]\n\tRtlClearBits [0x77A7B6CF+191]\n\n", "trace": "  File \"D:\\project\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\project\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\project\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 908, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\project\\project_01\\test_dir\\conftest.py\", line 56, in web_login\n    driver.get(url)\n  File \"D:\\project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 449, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"D:\\project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1681109372101, "stop": 1681109372102}], "start": 1681109372101, "stop": 1681109372138}